### PR TITLE
mobile optimization, accessibility fixes

### LINKED ISSUE #20: Adjust image used for "Developed-Open" tile
Learning accessibility experts indicated that the image used for the "Developed-open" tile is not easily visible at all levels and doesn’t seem to match the pattern used to show that land cover type on the left side of the screen.

Perhaps select a new image or zoom into existing texture.

Screen Shot 2020-05-28 at 1 46 19 PM

### LINKED ISSUE #21: Water column and other boxes overlap on small screens
See below screenshot. Options:

- Limit how small the screen size can be
- Unlock the width of the right sidebar

Note that many students access the site via Chromebooks or as part of the Learning Portal so the available space is even smaller.

Screen Shot 2020-05-28 at 1 48 34 PM

### LINKED ISSUE #22: Shortening screen does not shorten background image and arrows
Screen Shot 2020-05-28 at 1 53 07 PM

### PR DESCRIPTION
**Pull request by designmatty**
**Overview**
- Added lines around the arrow to help distinguish between arrow and background for accessibility purposes.
- Accessibility color updates
- Mobile friendly layout
    - Should look presentable down to 375px wide
    - Numerical stats arranged at top
    - sidebar sits below the model imagery
    - full page is now scrollable
    - All tooltips display in center of screen. (there was no way to keep them with their associated boxes as many of the tooltips rendered off screen)
- Updated imagery for "developed, open space"

**Demo**
Screen Shot 2020-07-28 at 11 38 17 AM
Screen Shot 2020-07-28 at 11 38 03 AM
Screen Shot 2020-07-28 at 11 38 37 AM

### CODE REVIEW

**Comment by designmatty** [comment]
- fixes https://github.com/WikiWatershed/mmw-micro/issues/21
- fixes https://github.com/WikiWatershed/mmw-micro/issues/20

**Comment by rajadain** [comment]
Taking a look

**Review by rajadain — APPROVED** [review]
+1 tested. This looks great.

Is it possible to have clicking outside the popup hide it? Currently only tapping the selected tile again makes it hide.

Nice work.

**Comment by designmatty** [comment]
@rajadain I added some logic to handle that request

**Review by rajadain — APPROVED** [review]
+1 sweet! Just tested and it works very well. Great job!!

**Pull request merged**
