### PR TITLE
Change "micro" to "runoff" in microsite subdomain

### PR DESCRIPTION
**Pull request by tnation14**
Fixes wikiwatershed/model-my-watershed#2641

# Testing
- https://runoff.staging.app.wikiwatershed.org
- https://runoff.app.wikiwatershed.org

### CODE REVIEW

**Review by rajadain — APPROVED** [review]
+1 sites work as expected. Nice!

Recommend holding off merging until we get final word from Stroud.

**Comment by rajadain** [comment]
Is it possible to add a redirect from the old URL to the new ones?

**Comment by tnation14** [comment]
Yes, I can to do it out of band once this is merged. I don't think it's necessary to capture in terraform, though.

**Comment by ajrobbins** [comment]
Stroud/ITSI folks are requesting that we either: 
 1) implement the redirect simultaneously to the URL change, so the link references still work, or
2) make the URL change take effect at night with some more advance warning to them

Thoughts on doing #1?

**Comment by tnation14** [comment]
Sure, I think #1 is doable.

**Comment by ajrobbins** [comment]
Great! When do you estimate we can put this into effect? No rush, just want to give them an estimated date/rough time.

**Comment by tnation14** [comment]
I'm going to start working on this now; I'll update with an exact timeframe once I test it out on staging.

**Comment by tnation14** [comment]
@ajrobbins staging URL & Redirect is live; I can take care of Production today whenever you give the OK.

**Comment by ajrobbins** [comment]
Go for it!

**Comment by tnation14** [comment]
Production and Staging URL renames/redirections are complete.

**Pull request merged**
