### PR TITLE
Update Site Name to "Runoff Simulation"

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Updates site name from "Micro Site Storm Model" to "Runoff Simulation".

Connects https://github.com/WikiWatershed/model-my-watershed/issues/2640

### Demo

image

Tagging @ajrobbins for visual review.

## Testing Instructions

* Check out this branch, run `update` and `server`
* Go to [:8000/](http://localhost:8000/)
* Ensure you see "Runoff Simulation" in the title, the tab header, and in the info box.

### CODE REVIEW

**Comment by ajrobbins** [comment]
The name should be "Runoff Simulation" (singular) - can you update to remove the extra s?

**Comment by rajadain** [comment]
Whoops sorry about that. Fixed now.

**Comment by kellyi** [comment]
screen shot 2018-02-12 at 7 13 46 pm

**Review by kellyi — APPROVED** [review]
:+1:

**Pull request merged**
